targets:
  $default:
    builders:
      source_gen:combining_builder:
        options:
          build_extensions:
            '^lib/data/api/models/responses/{{}}.dart': 'lib/data/api/models/responses/generated/{{}}.g.dart'